#!/bin/bash 

if [ $# == 0 ]; then
	ant clean && ant && ./sample-le/setup && ./scm/setup
elif [ $# -eq 1 ] && [ $1 == 'scm' ]; then
	ant clean && ant && ./scm/setup
elif [ $# -eq 1 ] && [ $1 == 'sample-le' ]; then
	ant clean && ant && ./sample-le/setup
else
	echo "usage: ./compile [optional : scm / sample-le]"
  exit 1
fi