#!/usr/bin/env bash

if [ $# -lt 7 ]; then
  echo "usage: genmc <mc_name> <num_node> <num_crash> <strategy> <working_dir> <use_ipc> <ipc_dir> [other_vars]"
  exit 1
fi

mc_name=$1
num_node=$2
num_crash=$3
strategy=$4
working_dir=$5
use_ipc=$6
ipc_dir=$7
other_vars=$8

echo mc_name=$mc_name > $working_dir/mc.conf
echo working_dir=$working_dir >> $working_dir/mc.conf
echo traversal_record_dir=$working_dir/state >> $working_dir/mc.conf
echo test_record_dir=$working_dir/record >> $working_dir/mc.conf
echo exploring_strategy=$strategy >> $working_dir/mc.conf
echo num_node=$num_node >> $working_dir/mc.conf
echo num_crash=$num_crash >> $working_dir/mc.conf
for var in $other_vars; do
  echo $var >> $working_dir/mc.conf
done
echo use_ipc=$use_ipc >> $working_dir/mc.conf
echo ipc_dir=$ipc_dir >> $working_dir/mc.conf