#!/usr/bin/env bash

if [ $# -lt 5 ]; then
  echo "usage: init <mc_name> <num_node> <num_crash> <strategy> <working_dir> [other_vars]"
  exit 1
fi

mc_name=$1
num_node=$2
num_crash=$3
strategy=$4
working_dir=$5
other_vars=$6

rm -r $working_dir/* 2> /dev/null

scriptdir=`dirname $0`

mkdir -p $working_dir/conf 
$scriptdir/genle $num_node $working_dir

$scriptdir/draftlemc $mc_name $working_dir

$scriptdir/genmc $mc_name $num_node $num_crash $strategy $working_dir "$other_vars"

mkdir $working_dir/record
mkdir $working_dir/state
mkdir $working_dir/console

mkdir $working_dir/bin
cp $scriptdir/resettest $working_dir/bin/resettest
cp $scriptdir/setlemc_testid $working_dir/bin/setlemc_testid

cp $scriptdir/dmck.conf $working_dir/dmck.conf

#mkdir $working_dir/log

cp $scriptdir/resource/le_log.properties $working_dir/
cp $scriptdir/resource/runnode $working_dir/
cp $scriptdir/resource/mc_log.properties $working_dir/
sed "s:WORKING_DIR:$working_dir:" $scriptdir/resource/testrunner.sh > $working_dir/testrunner.sh
chmod 755 $working_dir/testrunner.sh
cp $scriptdir/resource/monitorcheck.sh $working_dir/

